CREATE TABLE IF NOT EXISTS navigation_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255) UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    status ENUM('active', 'disabled') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS navbar_settings (
   id INT AUTO_INCREMENT PRIMARY KEY,
   color VARCHAR(7) NOT NULL DEFAULT '#ffffff',
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS body_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    color VARCHAR(7) NOT NULL DEFAULT '#ffffff',
    font_family VARCHAR(255) DEFAULT 'Arial',
    font_size VARCHAR(10) DEFAULT '16px',
    font_color VARCHAR(7) DEFAULT '#000000',
    line_height VARCHAR(10) DEFAULT '1.5',
    text_align VARCHAR(20) DEFAULT 'left',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

